# Generated by Django 5.0.8 on 2025-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='benefit',
            field=models.TextField(blank=True, default='Beneficio principal del servicio', help_text='Beneficio principal del servicio'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(default='Descripción del servicio', help_text='Descripción completa para la página de detalle'),
        ),
        migrations.AddField(
            model_name='service',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Requisitos o características (uno por línea)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default='Servicio profesional', help_text='Breve descripción para mostrar en la lista de servicios'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
