# Generated by Django 5.0.8 on 2025-09-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
